---
- name: refresh cache
  zypper_repository:
    runrefresh: yes
    repo: '*'

- name: Install python packages
  zypper:
    name: "{{ item }}"
    state: present
  with_items:
    - gcc
    - python
    - python3
    - python-devel
    - python3-devel
    - python-virtualenv
    - python3-virtualenv
    - python-pip
    - python3-pip
