---

- name: Download dotfiles
  git:
    repo: https://github.com/squidboylan/dotfiles.git
    clone: yes
    dest: "/home/{{ user_name }}"
    update: no

- name: "Create user {{ user_name }}"
  user:
    name: "{{ user_name }}"
    shell: /bin/bash

- name: Chown dotfiles
  file:
    owner: "{{ user_name }}"
    path: "/home/{{ user_name }}"
    recurse: yes
    group: "{{ group_name }}"
